### ISSUE TITLE
Nothing is displayed on the left after load

### ISSUE THREAD

**Issue by dingpanbao** [Tinfoilhat88/TModel#3]
Nothing is displayed on the left after load

**Comment by D3fa1t1** [comment]
Restart Your PC and check if the utocs/paks have been loaded

**Comment by dingpanbao** [comment]
Updated with a new version, now there are more logs
-Loading files
-Failed to download usmap
-Could not read "AthenaCharacterItemDefinition" correctly
-Could not read "AthenaCharacterItemDefinition" correctly
-Could not read "AthenaCharacterItemDefinition" correctly
...
