### ISSUE TITLE
Tmodel addon and app issue and emissions

### ISSUE THREAD

**Issue by waleed2004** [Tinfoilhat88/TModel#4]
hi i have some problems that page 14 of skin where the of skin are the textures are mess up like skin tropper shown red and mess up head and ghould troper is tshirt wrong 
and the addon eveytime i open blender i need to reinstall the addon
emission are there but not full support 
I hope U fix This issue in ur next update i really appretiate ur work 
keep up

**Comment by Tinfoilhat88** [comment]
I have tested those skins and they look just fine for me. Try completely removing the addon then re-installing (as done in [in this](https://youtu.be/xfOc2HVCya4?t=22)).

**Comment by waleed2004** [comment]
still have this problem and addon doesnt import all the time i need to reinstall it every time i launch blender

**Comment by waleed2004** [comment]
still have this problem and addon doesnt import all the time i need to reinstall it every time i launch blender
